# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5mofbjhnJ_gKU16FXAExuaJqjqKfcvx

Question 1
"""

nums = list(range(30, 65, 5))
print(nums)

nums.reverse()
print ('Reversed List:' , nums)

nums.insert(0, 65)
print(nums)

"""Question 2 """

blank = list()

for i in range(0, 21):
    blank.append(i)
print(blank)

blank.remove(0)
print(blank)

print(len(blank))
print(min(blank))
print(max(blank))

sum = sum(blank)
print(sum)

"""Question 3 """

weather = {"sunny": "play",
          "rainy": "watch TV",
          "cloudy": "walk"}
for condition, activity in weather.items():
  print('When '+ condition + ' let us ' + activity)

weather.update({"snowy": "ski"})
for condition, activity in weather.items():
  print('When '+ condition + ' let us ' + activity)