# -*- coding: utf-8 -*-
"""HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOUgxH1at5ryEcdSdKJFqUkMEqYH4APt
"""

def less_than(num):
  for n in range(num):
    print(n)
less_than(5)

"""Question 1"""

marks = {'Andy':88, 'Amy':66, 'James':90, 'Jules':55, 'Arthur': 77}

def student_grade(name):
    try:
      return marks[name]
    except:
      print(name+ ' not found')
student_grade('Andy')

def avg_function(dict_values): 
  return sum(marks.values()) / len(marks.values())
avg_function(marks.values())

"""Question 2 """

def printout(num):
  n=0
  while n < num: 
    print(n, (n**2))
    n += 1
printout(8)

"""Question 3"""

def add_integer(num):
  n = 1
  sum = 0
  while n <= num:
    sum = sum + n
    n = n + 1 
  print(sum)
add_integer(8)

"""Question 4"""

def sumfunction(num): 
  sum = 0
  for n in range(num):
    sum += n
    print(n, sum)
      
sumfunction(9)

"""Question 5"""

import numpy as np
def mean_sum_standarddeviation(range): 
  print("Mean:" , np.mean(range), "Sum:" , np.sum(range), "Standard deviation:", np.std(range))
mean_sum_standarddeviation(range(1,100))

"""Question 6 """

def minimal(v1, v2, v3, v4):
  print(min(v1, v2, v3, v4))
minimal(1,2,3,4)

"""Question 7"""

def statement(str1, str2, str3):
  print(f"Hello, {str1}. You are {str2} and a {str3}")
statement("Olivia", 20, "student")

list1 = [3, 4, 5, 20, 5, 25, 1, 3]
list1.pop(1)
print(list1)